Moved ed255... to an appendix
w3c/vc-di-eddsa pull request #36
Opened 2023-04-19 10:19 UTC by iherman

This is the result of a discussion in #32. The only change to the spec is to move the `Ed25519Signature2020` section to a (normative) appendix, leaving only `eddsa-2022` and `jcs-eddsa-2022` in the main "flow" of the spec. The message is that implementation should use `eddsa-2022` but, in view of the existing implementation, the older version is kept in the spec, albeit as an appendix.

Possible discussion points:

- At present, the `Ed2555..` section is _normative_. I am not sure this is really necessary; because it is, conceptually, deprecated, maybe an informative appendix would also do it for the practice
- I was tempted to remove the parenthetical "(eddsa-2022)" and the analogous "(Ed25519Signature2020)" from the subsection titles. I am not sure why they are present, but I wanted to get a feedback on that.
- I have added a small paragraph to the new appendix with its status. Otherwise it is unchanged
- I have marked the "Test Vectors" as non-normative as, I believe, it should be.

Fix #32

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/pull/36.html" title="Last updated on Apr 21, 2023, 12:32 PM UTC (48ae9d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/36/31eaa07...48ae9d1.html" title="Last updated on Apr 21, 2023, 12:32 PM UTC (48ae9d1)">Diff</a>

2023-04-20 22:27 UTC, msporny commented
Thank you for the PR, @iherman!

> * At present, the `Ed2555..` section is _normative_. I am not sure this is really necessary; because it is, conceptually, deprecated, maybe an informative appendix would also do it for the practice

I'd like to keep it normative so that a test suite is generated for it. Primarily because this cryptosuite has multiple implementations and is deployed in production.

> * I was tempted to remove the parenthetical "(eddsa-2022)" and the analogous "(Ed25519Signature2020)" from the subsection titles. I am not sure why they are present, but I wanted to get a feedback on that.

They're present largely because of the auto-links created by ReSpec, and because without them, it was easy to get which transformation/hashing/etc. algorithm you were looking at confused. I started out by not having the parentheticals and got confused multiple times while re-reading the spec... thinking I was looking at the hashing algorithm for a specific cryptosuite when I was actually looking at the wrong one.

> * I have added a small paragraph to the new appendix with its status. Otherwise it is unchanged.

+1

> * I have marked the "Test Vectors" as non-normative as, I believe, it should be.

+1

2023-04-20 22:32 UTC, msporny requested changes
+1 to this PR in general, but it needs to do at least two more things:

* Move the [Ed25519VerificationKey2020](https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/pull/36.html#ed25519verificationkey2020) to the Appendix.
* Move the [Ed25519Signature2020](https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/pull/36.html#ed25519signature2020) to the Appendix.

IOW, we are deprecating the key format, the signature format, and the algorithm for Ed25519*2020.

2023-04-21 12:36 UTC, iherman commented
> +1 to this PR in general, but it needs to do at least two more things:
> 
> * Move the [Ed25519VerificationKey2020](https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/pull/36.html#ed25519verificationkey2020) to the Appendix.
> * Move the [Ed25519Signature2020](https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/pull/36.html#ed25519signature2020) to the Appendix.
> 
> IOW, we are deprecating the key format, the signature format, and the algorithm for Ed25519*2020.

Damn! I missed that.

I have moved those into the appendix, and I have re-created the same text structure as in the original for a better reference. 

Note that I have made an additional change in the text because I believe that was a bug. The first paragraph of 2.2.1 said:

> Dereferencing the `verificationMethod` MUST result in an object containing a type property with the value set to `Ed25519SignatureKey2020`.

I presume that was a cut-and-paste result; the last reference says now `Multikey` instead.

2023-04-21 12:51 UTC, iherman commented
@msporny help with your git wizzardy... I see there are a bunch of merge conflicts now, probably because (it seems) a whole series of modifications on the file have been made by @davidlehn which probably involved the section I moved... What is the best way of settling those? (I quickly looked at a rebase and a merge of main into this branch and I was horrified:-)

2023-04-21 13:09 UTC, msporny commented
> @msporny help with your git wizzardy... I see there are a bunch of merge conflicts now, probably because (it seems) a whole series of modifications on the file have been made by @davidlehn which probably involved the section I moved... What is the best way of settling those? (I quickly looked at a rebase and a merge of main into this branch and I was horrified:-)

Yeah, changes like the one @davidlehn did (which was incredibly helpful -- but touches nearly the entire document) result in almost unrecoverable PRs. 

If I were you, I'd try the following:

1. create a NEW branch off of the latest `main`
2. cherry-pick your commits from this branch onto that one. 

and if that doesn't work, which it probably won't:

1. create a NEW branch off of the latest `main`
2. Re-create your changes and raise a new PR (or force push that new branch to this one). This will effectively be "starting from scratch".

Alas, there are a few diff's, like the one @davidlehn introduced that inevitably result in all other PRs having to be done over. There's no good time to do a PR like @davidlehn raised (unless you see zero PRs open, which is rare).

In any case, given that you're mostly just moving sections around @iherman, I hope a "start from scratch" approach to not take too long.

2023-04-21 13:33 UTC, iherman commented
I was afraid you would say that, @msporny... and I was hoping you had some magic wand up in your sleeve :-)

Anyway, I started from scratch and created #39. I will close this branch without action.

2023-04-21 13:33 UTC, closed without merging

2023-04-21 15:42 UTC, davidlehn commented
I'm happy I won the race to get merged first. :-)  Sorry for the trouble!