Update Sig2020 appendix for proof canonicalization.
w3c/vc-di-eddsa pull request #42
Opened 2023-04-26 17:42 UTC by Wind4Greg

Appendix A "The Ed25519Signature2020 Suite" is missing the canonicalization step for the *proof configuration*. This PR add the relevant steps and update. These steps are essentially the same as used in section "3.1.5 Proof Configuration (eddsa-2022)" and are necessary to conform with existing implementations and test vectors

2023-04-28 07:06 UTC, iherman commented
@Wind4Greg it is really great to see you contributing to these specs. The only thing is that these IPR warnings will keep popping up which is tiring for all of us I presume. Can you contact @brentzundel and @Sakurann to see whether you could sign up to the WG as an invited expert? That would make all this much smoother.

In the meantime... @msporny @dmitrizagidulin I would like your opinion whether these proposed changes are IPR sensitive or not. My gut feeling is they are not, but it is not for me to judge...

Thx

2023-04-28 13:03 UTC, msporny commented on index.html
> +  [[RDF-CANON]] to the <var>proofConfig</var>.
```suggestion
  Let <var>canonicalProofConfig</var> be the result of applying the
  Universal RDF Dataset Canonicalization Algorithm
  [[RDF-CANON]] to the <var>proofConfig</var>.
```

Good catch! Note that a similar change will need to be made to the jcs-eddsa-2022 and ecdsa-2019 algorithms as well.

2023-04-28 13:05 UTC, msporny commented on index.html
> +  to the <var>canonicalProofConfig</var>. <var>proofConfigHash</var> will be
This algorithm doesn't explain where `canonicalProofConfig` comes from... (I believe it comes in as input to the function, but we don't say that in the opening paragraph ... and probably should via a `<var>` declaration).

2023-04-28 13:06 UTC, msporny requested changes
Overall +1, with the only requested change being to say where `canonicalProofConfig` comes from.

2023-04-28 13:08 UTC, msporny commented
> In the meantime... @msporny @dmitrizagidulin I would like your opinion whether these proposed changes are IPR sensitive or not. My gut feeling is they are not, but it is not for me to judge...

They are not IPR sensitive, we can clear the IPR flag on this item.

2023-04-28 16:36 UTC, dlongley approved these changes

2023-04-28 16:36 UTC, dlongley commented on index.html
> +  to the <var>canonicalProofConfig</var>. <var>proofConfigHash</var> will be
Well, the "Proof Configuration" algorithm below now returns `canonicalProofConfig` *as* the `proofConfig`. So the only way to generate a `proofConfig` (which is an input to this algorithm here already) involves running that canonicalization step. So I don't think we need this change here -- and then we don't need to say where `canonicalProofConfig` comes from, because for `Ed25519Signature2020`, `proofConfig` *is* canonical / `canonicalProofConfig`.

So it seems that this PR already does what we need without any changes (without @msporny's suggestion here)?

2023-05-02 23:10 UTC, brentzundel commented
@Wind4Greg has joined the VCWG as an invited expert.

2023-05-03 15:31 UTC, dmitrizagidulin approved these changes
👍

2023-05-03 15:37 UTC, TallTed reviewed
lgtm, fwiw

2023-05-15 08:34 UTC, msporny approved these changes

2023-05-15 08:36 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-05-15 08:37 UTC, merged