Security Considerations: Added text on Ed25519 security properties.
w3c/vc-di-eddsa pull request #47
Opened 2023-05-25 15:50 UTC by Wind4Greg

Based on discussions concerning issue https://github.com/w3c/vc-di-eddsa/issues/45 I have come up with some *informative* text for the `security considerations` section. This text explains the relatively recent work that defines and proves security properties for Ed25519 signatures, how to achieve the highest levels of security, and cautions on Ed25519 library implementations.

Note that I didn't see an "easy way" to include mathematical notation with ReSpec so used MathML (a W3C specification) which is somewhat verbose and not hand editable. Some online math editors such as [LaTex Editor](https://latexeditor.lagrida.com/) can produce MathML output if you want to edit any of the equations.

Cheers Greg

***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-eddsa/pull/47.html" title="Last updated on Jun 1, 2023, 6:24 PM UTC (ea626af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/47/8031fd9...Wind4Greg:ea626af.html" title="Last updated on Jun 1, 2023, 6:24 PM UTC (ea626af)">Diff</a>

2023-06-01 14:05 UTC, TallTed requested changes

2023-06-01 14:05 UTC, TallTed commented on index.html
> +curve) due to the compact size of the keys and signatures, and the speed at
```suggestion
        <p>Ed25519 signatures (EdDSA algorithm with edwards25519 curve) have
        been widely adopted, due both to the compact size of the keys and
        signatures and to the speed at 
```

2023-06-01 14:05 UTC, TallTed commented on index.html
> +create and verify Ed25519 signatures. Since the publication of [[RFC8032]]
```suggestion
create and verify Ed25519 signatures. Since the publication of [[RFC8032]],
```

2023-06-01 14:05 UTC, TallTed commented on index.html
> +[[Provable_Ed25519]] and [[Taming_EdDSAs]]. However it was observed that a
```suggestion
security properties of Ed25519 signatures have been rigorously proven (see
[[Provable_Ed25519]] and [[Taming_EdDSAs]]). However, it has been observed that a
```

2023-06-01 14:05 UTC, TallTed commented on index.html
> +significant number of libraries do not achieve these security properties due to
```suggestion
significant number of libraries do not achieve these security levels, due to 
```

2023-06-01 14:05 UTC, TallTed commented on index.html
> +properties.
```suggestion
this section, we summarize the security levels achievable with Ed25519 
signatures, and indicate how one can determine whether a library will support those 
levels.
```

2023-06-03 19:14 UTC, msporny approved these changes
LGTM. Bonus points for using MathML! :)

2023-06-03 19:14 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-06-03 19:15 UTC, merged