Add Greg and Sebastian as Editors.
w3c/vc-di-eddsa pull request #50
Opened 2023-07-09 21:00 UTC by msporny

This PR adds Greg and Sebastian as Editors. The PR shouldn't be processed until after Sebastian's IE application has been processed. /cc @Wind4Greg @seabass-labrax

2023-07-10 06:14 UTC, iherman commented
> This PR adds Greg and Sebastian as Editors to the EdDSA Cryptosuites. The PR shouldn't be processed until after Sebastian's IE application has been processed. /cc @Wind4Greg @seabass-labrax
>

I agree, but we have never received a formal application of @seabass-labrax (only an informal request to the chairs). Sebastian, you should fill [the application form](https://www.w3.org/groups/wg/vc/apply-as-invited-expert/).

2023-07-11 10:07 UTC, seabass-labrax requested changes

2023-07-11 10:07 UTC, seabass-labrax commented on index.html
> +          company: "Invited Expert", w3cid: 0
```suggestion
          company: "Invited Expert", w3cid: 140132
```

2023-07-13 21:53 UTC, msporny commented on index.html
> +          company: "Invited Expert", w3cid: 0
```suggestion
          company: "Invited Expert", w3cid: 140479
```

2023-07-14 14:08 UTC, dmitrizagidulin approved these changes

2023-07-14 14:19 UTC, merged

2023-07-14 16:50 UTC, brentzundel commented
Minor concern here that at this point Sebastian has been accepted as an Invited Expert, but not yet joined the VCWG.

2023-07-14 17:19 UTC, msporny commented
> Minor concern here that at this point Sebastian has been accepted as an Invited Expert, but not yet joined the VCWG.

Yes, he is reading through the IPR policy and WG Charter to make sure he knows what he's signing up for... we were going to wait to merge this until he had joined the WG. 

I guess at this point, we can just not accept PRs from him until he has joined the WG.