Unify error codes and error handling language
w3c/vc-di-eddsa pull request #84
Opened 2024-06-24 21:19 UTC by Wind4Greg

This PR addresses issue https://github.com/w3c/vc-di-eddsa/issues/82.
It updates the document to use three main error codes (PROOF_TRANSFORMATION_ERROR, PROOF_GENERATION_ERROR, and PROOF_VERIFICATION_ERROR. ) and adds appropriate language on raising and conveying errors where appropriate.

2024-06-24 22:10 UTC, TallTed requested changes
Just a few, to make all these requirements read consistently.

2024-06-24 22:10 UTC, TallTed commented on index.html
> +set to the string `eddsa-rdfc-2022` then an error MUST be raised and SHOULD
```suggestion
set to the string `eddsa-rdfc-2022`, an error MUST be raised and SHOULD
```

2024-06-24 22:10 UTC, TallTed commented on index.html
>  set to the string `eddsa-jcs-2022` then an error MUST be raised that
```suggestion
set to the string `eddsa-jcs-2022`, an error MUST be raised and
```

2024-06-24 22:10 UTC, TallTed commented on index.html
> +SHOULD use the `PROOF_VERIFICATION_ERROR` error code.
```suggestion
SHOULD convey an error type of `PROOF_VERIFICATION_ERROR`.
```

2024-06-28 13:33 UTC, iherman approved these changes

2024-06-28 16:33 UTC, dlongley approved these changes

2024-06-28 19:13 UTC, Wind4Greg commented
@TallTed can you look at this again. I also used "data-cite" links for the error codes per recommendation from @iherman.

2024-06-28 23:02 UTC, Wind4Greg commented
@TallTed please check this again. I got weird merge conflicts when I added links for the error codes (to the DI spec) and don't know if I lost some of the edits.

2024-06-30 16:15 UTC, msporny approved these changes

2024-06-30 16:16 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-06-30 16:16 UTC, merged